### ISSUE TITLE
vs code 无法设置为默认格式化

### ISSUE THREAD

**Issue by 60liulin60** [wuxianqiang/WeChat-Snippets#44]
![企业微信截图_a820b1a0-1e0a-44a6-a032-e7128bce59f1](https://github.com/wuxianqiang/WeChat-Snippets/assets/49518510/5a6037cc-f48f-48c4-ac82-c9a3aae03c5c)
安装后 无法设置为默认格式

**Comment by 60liulin60** [comment]
![image](https://github.com/wuxianqiang/WeChat-Snippets/assets/49518510/d0054172-3a05-4254-b812-0f70f30c2d80)

**Comment by wuxianqiang** [comment]
建议你重新启动一下呢？
