### ISSUE TITLE
和 tailwindcss 的代码提示插件冲突

### ISSUE THREAD

**Issue by shebaoting** [wuxianqiang/WeChat-Snippets#45]
和 tailwindcss 的代码提示插件冲突。开启你的插件以后，tailwindcss 的代码提示就失效了。

**Comment by wuxianqiang** [comment]
你是要在 wxml 中使用 tailwindcss 功能吗？这个确实是不支持，如果是 html 文件是可以正常 tailwindcss 功能的

**Comment by wuxianqiang** [comment]
![2683656aeb85e6e54572d4ce1296f682](https://github.com/wuxianqiang/WeChat-Snippets/assets/26681854/9e0aabff-8f50-482b-a1d6-0bd13495964d)
需要你在设置中添加一个配置
