### ISSUE TITLE
无法正确切换提示

### ISSUE THREAD

**Issue by noprogram-programmer** [wuxianqiang/WeChat-Snippets#6]
按照步骤安装了，vetur和prettier，任然无法正确提示

**Comment by wuxianqiang** [comment]
默认是提示微信的指令，如果想要修改成支付宝的指令提示，需要打开设置->扩展->小程序->配置小程序的类型，然后选择支付宝小程序，最后重新启动编辑器。

JS的提示需要安装@types/wechat-miniprogram

**Comment by noprogram-programmer** [comment]
> 默认是提示微信的指令，如果想要修改成支付宝的指令提示，需要打开设置->扩展->小程序->配置小程序的类型，然后选择支付宝小程序，最后重新启动编辑器。
> 
> JS的提示需要安装@types/wechat-miniprogram

xml后缀无法提示属性语法..... JS文件也存在无法提示的问题

**Comment by wuxianqiang** [comment]
能提供一下代码示例吗？
